### ISSUE TITLE
Add the plugin emf4che to Eclipse Che

### ISSUE THREAD

**Issue by 19yak** [eclipsesource/emf4che#15]
@mathansen 

I try to **add** the plug-in **emf4che** to **Che**,
in step did any own can help me.
My Eclipse Che **version** is **5.1.2**

Finally you need to make sure the <version> in all the POM files under */plugins/plugin-emf* match with your Che version (i.e. compare with your parent POM). This includes the files:
- */plugins/plugin-emf/pom.xml*
- */plugins/plugin-emf/che-plugin-emf-ide/pom.xml*
- */plugins/plugin-emf/che-plugin-emf-server/pom.xml*
- */plugins/plugin-emf/che-plugin-emf-shared/pom.xml*

**Comment by 19yak** [comment]
@mathansen 

the step to run Che:
what is module that required to be builded:

1. the plug-in root folder and sub-folder(emf-ide, emf-server and emf-shared)
2. assembly-ide-war
3. assembly-wsagent-war
4. assembly-main
5. che root??

**Comment by JonasHelming** [comment]
Please follow the update docu in README

**Comment by 19yak** [comment]
Hello,

I can ask a question about the possibility of developing a graphic editor
in AngularJS, Bootstrap, JointJS.
And the ability to integrate this editor with gwt

>
