### ISSUE TITLE
Update the documentation on how to build the plugin

### ISSUE THREAD

**Issue by JonasHelming** [eclipsesource/emf4che#16]
As we have update the build to build against the binaries, we need to update the documentation in the README accordingly

**Comment by 19yak** [comment]
@JonasHelming Can I find the source not updated (an older version) of Emf4che compatible with the documentation to test this plug-in.

**Comment by JonasHelming** [comment]
We are currently trying to fix that. I do not think, there is a way to roll back.

Based on the other questions that you have send me on other channels, I assume you want to create a custom plugin for Che. Have you followed the official documentation on how to do that?

**Comment by 19yak** [comment]
Absolutely that yes I follow the documentation of Che under Eclipse. So I
test all the plugins available with the Che source.

Now I am looking for answers to my questions:

- How to develop a UML plugin for Che?
- Can we extend the "text editor" by a graphic editor?
- Working with GWT or HTML and JS native?
- APIs, frameworks (JointJS, GoJS, Vaadin ...)?

**Comment by JonasHelming** [comment]
I would start with selecting an existing graphical framework. I would probably search in the HTML/JS area, first. I would do some prototyping to select one of those frameworks. That means, I would build a first version of the UML editor stand-alone as a plain web application.
Finally, I would embed this editor into Che as described here:
https://www.eclipse.org/che/docs/plugins/embed-htmljs/index.html

**Comment by 19yak** [comment]
For the choice of a javascript modeling framework. Can you tell me to use a
particular one?

**Comment by 19yak** [comment]
For me the technological choices are not yet fixed. I am currently
documenting tools, frameworks and open source libraries (Javascript and
HTML) that I can use them to get to my goal "UML graphical editor.

**Comment by JonasHelming** [comment]
Yes, you should research on that, I cannot recommend a particular one...

**Comment by sdirix** [comment]
Updated the documentation
