### ISSUE TITLE
Build failure due non-resolvable parent pom 

### ISSUE THREAD

**Issue by mattsse** [eclipsesource/emf4che#21]
I tried to build from the parent folder with
`mvn clean install`

This results in a maven fatal error

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.eclipsesource.emf:eclipsesource-ide-parent:1.0.0-SNAPSHOT: Could not find artifact org.eclipse.che.depmgt:maven-depmgt-pom:pom:5.5.0-SNAPSHOT in codenvy-public-repo (https://maven.codenvycorp.com/content/groups/public/) and 'parent.relativePath' points at wrong local POM @ line 16, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.eclipsesource.emf:eclipsesource-ide-parent:1.0.0-SNAPSHOT (/Users/Matthias/git/emf4che/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.eclipsesource.emf:eclipsesource-ide-parent:1.0.0-SNAPSHOT: Could not find artifact org.eclipse.che.depmgt:maven-depmgt-pom:pom:5.5.0-SNAPSHOT in codenvy-public-repo (https://maven.codenvycorp.com/content/groups/public/) and 'parent.relativePath' points at wrong local POM @ line 16, column 13 -> [Help 2]

I could get passed this by upgrading the version of the `maven-depmgt-pom` artifact and the `che.version` property in the parent pom to `5.6.0-SNAPSHOT` 
Due to API changes in the `org.eclipse.che.ide.newresource.AbstractNewResourceAction` class. I additionally had to adjust the `org.eclipse.che.plugin.emf.ide.editor.NewGenmodelFileAction` and `org.eclipse.che.plugin.emf.ide.editor.NewEcoreFileAction` Constructors in the `che-plugin-emf-id` plugin respectively.
After that `mvn clean install` is executed successfully again.

**Comment by SancezZ** [comment]
I think this is correct. There is no 5.5.0-SNAPSHOT anymore. It was released on 22.03.2017 https://github.com/eclipse/che/releases/tag/5.5.0 .

I my opinion you can use the nightly build 5.6.0-SNAPSHOT or simply use the 5.5.0 .

**Comment by sdirix** [comment]
Thanks @MattsSe for raising the issue and thanks @SancezZ for your helpful suggestion. For now the build was updated to the 5.5.0 release. We will of course look into supporting later versions in the future as well.

Feel free to comment if you have further problems with the current build.

**Comment by mathansen** [comment]
We migrated to Che v. 5.11.0 a few days ago. Closing this issue.
