### ISSUE TITLE
emf4che build needs about 10Gb of memory

### ISSUE THREAD

**Issue by neilmackenzie** [eclipsesource/emf4che#23]
This is not a bug, but on my  linux environment (centos 7) the emf4che build fails unless I have about 10Gb of memory (physical plus swap).
The error message is not very clear, and it took me some time to find the cause, so maybe a note in the readme or requirements would help others if they hit the same problem (which is perhaps likely if compiling on a laptop). Increasing the swap size was the easy fix for me.
The issue seems to be the gwt-maven-plugin uses a lot of memory, so I don't think it is an issue with the emf4che build.
The error seen is:

[INFO] Che IDE :: Assembly :: Agent Server ................ SUCCESS [ 26.124 s]
[INFO] Che IDE :: Assembly :: Compiling GWT Application ... FAILURE [03:13 min]
[INFO] Che IDE :: Assembly :: Assemblies Tomcat ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:43 min (Wall Clock)
[INFO] Finished at: 2017-05-26T09:12:46+01:00
[INFO] Final Memory: 125M/1835M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.8.0:compile (default) on project assembly-ide-war: Command [[
[ERROR] /bin/sh -c '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-2.b11.el7_3.x86_64/jre/bin/java' '-Xss512m' '-Xmx2048m' 'com.google.gwt.dev.Compiler' '-logLevel' 'INFO' '-war' '/home/neil/git/emf4che/assembly/assembly-ide-war/target/assembly-ide-war-1.0.0-SNAPSHOT' '-localWorkers' '4' '-XfragmentCount' '-1' '-sourceLevel' '1.8' '-gen' '/home/neil/git/emf4che/assembly/assembly-ide-war/target/.generated' 'com.eclipsesource.emf.ide.IDE'
[ERROR] ]] failed with status 137

**Comment by mathansen** [comment]
Hi @neilmackenzie, thank you for reporting this. We traced the problem to the JVM heap configuration which used to be quite generous. Please adjust the settings in .mvn/jvm.config to fit your build environment (-Xms and -Xmx flags).
